/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IGala:menuLeft': typeof import('~icons/gala/menu-left')['default']
    'IIconParkOutline:down': typeof import('~icons/icon-park-outline/down')['default']
    'ILucide:calendar': typeof import('~icons/lucide/calendar')['default']
    'ILucide:clock': typeof import('~icons/lucide/clock')['default']
    'ILucide:coins': typeof import('~icons/lucide/coins')['default']
    'ILucide:dot': typeof import('~icons/lucide/dot')['default']
    'ILucide:download': typeof import('~icons/lucide/download')['default']
    'ILucide:info': typeof import('~icons/lucide/info')['default']
    'ILucide:mapPin': typeof import('~icons/lucide/map-pin')['default']
    'ILucide:sun': typeof import('~icons/lucide/sun')['default']
    IMaterialSymbolsAgriculture: typeof import('~icons/material-symbols/agriculture')['default']
    KPICard: typeof import('./src/components/KPICard.vue')['default']
    KPICards: typeof import('./src/components/KPICards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    StatusCard: typeof import('./src/components/StatusCard.vue')['default']
    TheBarChart: typeof import('./src/components/TheBarChart.vue')['default']
    TheGauge: typeof import('./src/components/TheGauge.vue')['default']
    TheLineChart: typeof import('./src/components/TheLineChart.vue')['default']
    TheRadarChart: typeof import('./src/components/TheRadarChart.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTableChart: typeof import('./src/components/TheTableChart.vue')['default']
    TheWeather: typeof import('./src/components/TheWeather.vue')['default']
  }
}
